// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCaC1YIn3TQox1Jvbeybq52s1oXZ_Sdvo',
    appId: '1:689891334182:web:f96f96b6620c75f3f36ee7',
    messagingSenderId: '689891334182',
    projectId: 'hospital-management-syst-791ab',
    authDomain: 'hospital-management-syst-791ab.firebaseapp.com',
    storageBucket: 'hospital-management-syst-791ab.firebasestorage.app',
    measurementId: 'G-8EQD54CE7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrmCGoSCAnu6UfcgoU4hkXYvpnWFObKv8',
    appId: '1:689891334182:android:c9fe4b73fe646aedf36ee7',
    messagingSenderId: '689891334182',
    projectId: 'hospital-management-syst-791ab',
    storageBucket: 'hospital-management-syst-791ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaJN7ieEx9364FN5c2NUKHN1mutbLY7-I',
    appId: '1:689891334182:ios:77a82e9dcba597c8f36ee7',
    messagingSenderId: '689891334182',
    projectId: 'hospital-management-syst-791ab',
    storageBucket: 'hospital-management-syst-791ab.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaJN7ieEx9364FN5c2NUKHN1mutbLY7-I',
    appId: '1:689891334182:ios:77a82e9dcba597c8f36ee7',
    messagingSenderId: '689891334182',
    projectId: 'hospital-management-syst-791ab',
    storageBucket: 'hospital-management-syst-791ab.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCaC1YIn3TQox1Jvbeybq52s1oXZ_Sdvo',
    appId: '1:689891334182:web:2095061269666f6df36ee7',
    messagingSenderId: '689891334182',
    projectId: 'hospital-management-syst-791ab',
    authDomain: 'hospital-management-syst-791ab.firebaseapp.com',
    storageBucket: 'hospital-management-syst-791ab.firebasestorage.app',
    measurementId: 'G-RSH1DM465P',
  );

}